config/routes.rb
Rails.application.routes.draw do

  resources :users, :except => [:show] do
    member do
      get :delete
    end
  end

  root :to =>  'search#index'

  get 'search/found', :as => 'found_word'

  get 'search/index'
  get 'search/found'
  get 'search/notFound'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :words

  has_secure_password

  EMAIL_REG = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i


  validates_presence_of :first_name
  validates_length_of :first_name, :maximum => 25
  validates_presence_of :last_name
  validates_length_of :last_name, :maximum => 50
  validates :username,  :presence => true,
            :uniqueness => true,
            :length => {:within => 2...25}

  validates :email, :presence => true,
            :length => {:maximum => 50},
            :uniqueness => true,
            :format => { :with => EMAIL_REG},
            :confirmation => true
  scope :sorted, lambda { order("first_name ASC") }


end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in."
      redirect_to(root_path)
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def create
  end
end

app/controllers/search_controller.rb
require 'net/http'
require 'json'
require 'uri'

class SearchController < ApplicationController
  def index
  end

  def found
    @word = Word.where(:word => params[:search_term]).first
    if @word.nil?
      response = request_word_from_api(params[:search_term].delete(' '))
      if response.to_s.include? "No Definitions Found"
        redirect_to("/search/notFound")
      else
        @word = Word.new
        @word.word = response[0]["word"]
        @word.count = 1
        @word.audio = response[0]["phonetics"][0]["audio"]
        @word.origin = response[0]["origin"]
        @word.partOfSpeech = response[0]["meanings"][0]["partOfSpeech"]
        @word.definition = response[0]["meanings"][0]["definitions"][0]["definition"]
        @word.example = response[0]["meanings"][0]["definitions"][0]["example"]
        @word.save
      end
    else
      if @word.count.nil?
        @word.count = 1
      else
        @word.count+=1
      end
      @word.save
    end

  end

  def notFound
  end

  private

  def request_word_from_api(word)
    uri = URI("https://api.dictionaryapi.dev/api/v2/entries/en/" + word.to_s)
    Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
      request = Net::HTTP::Get.new(uri, 'Content-Type' => 'application/json')
      request.body = {parameter: 'value'}.to_json
      response = http.request request # Net::HTTPResponse object
      JSON.parse(response.body)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :confirm_logged_in, :except => [:new, :create, :index]

  def index
    @users = User.sorted
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "admin user saved successfully."
      redirect_to(root_path)
    else
      render(new_user_path)
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User had updated successfully"
      redirect_to(root_path)
    else
      render('edit')
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User has been deleted."
    redirect_to(root_path)
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :username
    )
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

  def show_nav_bar
    render(:partial => 'application/nav_bar')
  end

  def status_tag(boolean, options={})
    options[:true_text]  ||= ''
    options[:false_text] ||= ''

    if boolean
      content_tag(:span, options[:true_text], :class => 'status true')
    else
      content_tag(:span, options[:false_text], :class => 'status false')
    end
  end

end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_nav_bar.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="form-inline nav-left">
    <button class="btn btn-outline-success my-2 my-sm-0" type="button"> <%= link_to 'Search', root_path %></button>
    <button class="btn btn-sm btn-outline-secondary my-2 my-sm-0" type="button"><%= link_to 'Sign up', new_user_path %></button>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lexicon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/found.html.erb
<%= show_nav_bar %>
<div class="card center-card" >
  <div class="card-body center-card">
    <h5 class="card-title"><b>Word : </b> <%= @word.word %></h5>
    <p class="card-text"><b>Definition : </b> <%= @word.definition %></p>
    <p class="card-text"><b>Part Of Speech : </b> <%= @word.partOfSpeech %></p>
    <p class="card-text"><b>Example : </b> <%= @word.example %></p>
    <p class="card-text"><b>Origin : </b> <%= @word.origin %></p>
<br/>
    <div class="col-sm-4 col-sm-offset-4 embed-responsive embed-responsive-4by3">
    <audio controls>
      <source src="<%= @word.audio %>" type="audio/mpeg">
    </audio>
    </div>
  </div>
</div>
</p>

app/views/search/index.html.erb
<%= show_nav_bar %>
<h1 class="heading-center">Lexicon</h1>
<div class="container">
  <div class="row search_height d-flex justify-content-center align-items-center">
    <div class="col-md-8">
      <div class="search"> <i class="fa fa-search"></i>
        <%= form_tag(found_word_path, :method => :get) do %>
        <input type="text" class="form-control" name="search_term" placeholder="Enter a word">
          <button class="btn btn-primary" type="submit" >Search</button> </div>
        <% end %>
    </div>
  </div>
</div>

app/views/search/notFound.html.erb
<%= show_nav_bar %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="error-template">
        <h1>
          Oops!</h1>
        <h2>
          404 Not Found</h2>
        <div class="error-details">
          Sorry, an error has occurred, Requested page not found!
        </div>
        <button class="btn btn-primary" ><%= link_to 'Home', search_index_url %></button>

      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>
<table summary="User form fields">
  <tr>
    <th><%= f.label(:first_name) %></th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:email) %></th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th><%= f.label(:username) %></th>
    <td><%= f.text_field(:username) %></td>
  </tr>
  <tr>
    <th><%= f.label(:password) %></th>
    <td><%= f.password_field(:password) %></td>
  </tr>
</table>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<% @page_title = "Delete Admin User" %>

<%= link_to("<< Back to Search", root_path, :class => 'back-link') %>

<div class="admin-users delete">
  <h2>Delete User</h2>

  <%= form_for(@user, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this user?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete User") %>
    </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<% @page_title = "Update Admin User" %>

<%= link_to("<< Back to Search", root_path, :class => 'back-link') %>

<div class="admin-users edit">
  <h2>Update Admin User</h2>

  <%= form_for(@user) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update User") %>
    </div>

  <% end %>
</div>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/new.html.erb
<%= show_nav_bar %>
<% @page_title = "New Admin User" %>

<div class="users-new">
  <h2>Sign Up</h2>

  <%= form_for(@user) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="btn btn-primary">
      <%= f.submit("Create Account") %>
    </div>

  <% end %>
</div>